package:
  name: libelemental
  version: "0.87.5"

source:
  git_url: https://github.com/elemental/Elemental.git

build:
  features:
    - xdata

  rpaths:
    - lib/
    - lib64/

requirements:
  build:
    - gcc >=4.8.5
    - python >=2.7,<3
    - openblas
    - mpich2
    - git
    - cmake >=2.8
  
  run:
    - libgcc	
    - python >=2.7,<3
    - openblas
    - mpich2
    - numpy
    - matplotlib
    - networkx

about:
  home: http://libelemental.org
  license: New BSD license
  summary: 'C++ library for distributed memory linear algebra and optimization'
